@host = 192.168.1.2:11111

### signup
POST http://{{host}}/auth/signup
Content-Type: application/json

{
    "email":"ffffasdf@naver.com",
    "password": "asdf", 
    "nickname": "asdf"
}
###

### login
POST http://{{host}}/auth/login
Content-Type: application/json

{
    "email":"sssang977",
    "password": "asdf"
}
###

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhc2RmIiwiZXhwIjo0NzYzMDEzNjk0fQ.--PMVH0Bupk5-IaMe2FJPJ6yX54hau2EoMB5ArmTvC4

###
GET http://{{host}}
Content-Type: application/json
Authorization: {{token}}

{
}
###