@host = 192.168.1.2:11111

### 회원가입
POST http://{{host}}/auth/signup
Content-Type: application/json

{
    "email":"foobar2@naver.com",
    "password": "asdf", 
    "nickname": "김불닭"
}
###

### 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
    "email":"foobar2@naver.com",
    "password": "asdf"
}
###

### 액세스 토큰 갱신
PUT http://{{host}}/auth/refresh
Content-Type: application/json

{
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX3R5cGUiOiLquYDrtojri60iLCJleHAiOjE2NDY0MDIzNjN9.adeeA0eg2UwSag2WUR1vPUk1k1hcD45n38QI2OUI2ug"
}
###

### 로그아웃
DELETE http://{{host}}/auth/logout
Content-Type: application/json

{
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX3R5cGUiOiLquYDrtojri60iLCJleHAiOjE2NDY0MDIzNjN9.adeeA0eg2UwSag2WUR1vPUk1k1hcD45n38QI2OUI2ug"
}
###

### 내 정보 조회
GET http://{{host}}/user/my-info
Content-Type: application/json

{
}
###

### 회원탈퇴
DELETE http://{{host}}/user/close-my-account
Content-Type: application/json

{
}
###

###
GET http://{{host}}
Content-Type: application/json

{
}
###

### 문서 등록
POST http://{{host}}/doc/document
Content-Type: application/json

{
    "title": "foo", 
    "content": "으악asfdqwdqwdqw22"
}
###

###
GET http://{{host}}/doc/history?title=foo
Content-Type: application/json

{
    "title": "테스트2", 
    "content": "으악"
}
###

### 롤백하기
POST http://{{host}}/doc/history/rollback
Content-Type: application/json

{
    "history_id": 5
}
###

###
GET http://{{host}}/doc/history/detail?history_id=4
Content-Type: application/json

{
    "title": "테스트2", 
    "content": "으악"
}
###

###
GET http://{{host}}/doc/search?search_text=
Content-Type: application/json

{
    "search_text": "테스트2", 
    "content": "내용2"
}
###

###
GET http://{{host}}/doc/document?title=1234
Content-Type: application/json

{
}
###

###
POST http://{{host}}/doc/debate
Content-Type: application/json

{
    "document_title": "foo",
    "subject":"주제1",
    "content":"내용1"
}
###

###
POST http://{{host}}/doc/debate/comment
Content-Type: application/json

{
    "debate_id": 1,
    "content":"내용1"
}
###


###
GET http://{{host}}/doc/debate-list?document_title=foo&open_yn=true
Content-Type: application/json

{
    "debate_id": 1,
    "content":"내용1"
}
###