@host = 192.168.1.2:11111

### 액세스 토큰 갱신
PUT http://{{host}}/auth/refresh
Content-Type: application/json

{
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX3R5cGUiOiLquYDrtojri60iLCJleHAiOjE2NDY0MDIzNjN9.adeeA0eg2UwSag2WUR1vPUk1k1hcD45n38QI2OUI2ug"
}
###

### 로그아웃
DELETE http://{{host}}/auth/logout
Content-Type: application/json

{
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX3R5cGUiOiLquYDrtojri60iLCJleHAiOjE2NDY0MDIzNjN9.adeeA0eg2UwSag2WUR1vPUk1k1hcD45n38QI2OUI2ug"
}
###

### signup
GET http://{{host}}/foo
Content-Type: application/json

{
}
###

### 내 정보 조회
GET http://{{host}}/user/my-info
Content-Type: application/json

{
}
###

### 회원탈퇴
DELETE http://{{host}}/user/close-my-account
Content-Type: application/json

{
}
###

### signup
POST http://{{host}}/auth/signup
Content-Type: application/json

{
    "email":"foobar2@naver.com",
    "password": "asdf", 
    "nickname": "김불닭"
}
###

### signup
POST http://{{host}}/auth/signup
Content-Type: application/json

{
    "email":"foobar354@naver.com",
    "password": "asdf", 
    "nickname": "김불닭"
}
###

### login
POST http://{{host}}/auth/login
Content-Type: application/json

{
    "email":"foobar354@naver.com",
    "password": "asdf"
}
###

### login
DELETE http://{{host}}/auth/logout
Content-Type: application/json

{
    "refresh_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJVU0VSIiwiZXhwIjoxNjQ5Mjg4NDk2fQ.Z7J0RDYPToW1CblK6_1n-TTGAnocsa2FH7o9r6E6XFM"
}
###

###
GET http://{{host}}
Content-Type: application/json

{
}
###

###
POST http://{{host}}/doc/document
Content-Type: application/json

{
    "title": "테스트2", 
    "content": "으악"
}
###

###
GET http://{{host}}/doc/history?title=main
Content-Type: application/json

{
    "title": "테스트2", 
    "content": "으악"
}
###

###
GET http://{{host}}/doc/history/detail?history_id=0
Content-Type: application/json

{
    "title": "테스트2", 
    "content": "으악"
}
###

###
GET http://{{host}}/doc/search?search_text=
Content-Type: application/json

{
    "search_text": "테스트2", 
    "content": "내용2"
}
###

###
GET http://{{host}}/doc/document?title=1234
Content-Type: application/json

{
}
###